on: [push, pull_request]
name: Tests and code
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: juampynr/drupal8ci:latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
        ports:
          - "33306:3306"

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build project
        run: |
          robo job:build

      - name: Run PHPUnit tests
        run: vendor/bin/robo job:unit-tests

  code-standards:
    runs-on: ubuntu-latest
    container:
      image: juampynr/drupal8ci:latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build project
        run: |
          robo job:build

      - name: Check coding standards
        run: vendor/bin/robo job:coding-standards

#  code-coverage:
#    runs-on: ubuntu-latest
#    container:
#      image: juampynr/drupal8ci:latest
#
#    services:
#      mysql:
#        image: mysql:5.7
#        environment:
#          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
#          MYSQL_DATABASE: drupal
#          MYSQL_USER: drupal
#          MYSQL_PASSWORD: drupal
#        ports:
#          - "33306:3306"
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#
#      - name: Build project
#        run: |
#          robo job:build
#
#      - name: Assess code coverage
#        run: |
#          vendor/bin/robo job:coverage-report
#
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v1
#        with:
#          name: coverage
#          path: coverage

  install-from-config:
    runs-on: ubuntu-latest
    container:
      image: juampynr/drupal8ci:latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
        ports:
          - "33306:3306"

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build project
        run: |
          robo job:build

      - name: Install from config
        run: |
          vendor/bin/robo job:install-from-config

      - name: Migrate content
        run: |
          vendor/bin/robo job:migrate-content

      - name: Run existing site tests
        run: |
          vendor/bin/robo run:chrome-headless &
          vendor/bin/robo job:existing-site-tests
